rules:
 type-empty: [2, never]
 type-enum: [2, always, [fix, feat, doc, perf, refactor, style, test, chore]]
 subject-empty: [2, never]
 body-leading-blank: [2, always]
 footer-leading-blank: [2, always]
