# syntax=docker/dockerfile:1

ARG  PY_VERSION={{PYTHON_VERSION}}
FROM python:${PY_VERSION}-buster

WORKDIR /{{PROJECT_NAME}}

# RUN apt-get update && apt-get upgrade -y && apt-get install make git gcc libpq-dev -y --no-install-recommends

COPY requirements/requirements.in requirements/requirements.in
COPY requirements/requirements_dev.in requirements/requirements_dev.in
COPY LICENSE MANIFEST.in versioneer.py setup.py pyproject.toml README.md Makefile ./
COPY .git .git
COPY {{SRC}} {{SRC}}
COPY tests tests

RUN addgroup --system tester && adduser --system --group tester
RUN chown -R tester:tester /{{PROJECT_NAME}}

# change to the tester user: switch to a non-root user is a best practice.
USER tester
ENV PATH ${PATH}:/home/tester/.local/bin

CMD make checks
